# Install MacOS Applications
brew install --cask google-chrome
brew install --cask firefox
brew install --cask spotify
brew install --cask discord
brew install --cask visual-studio-code
brew install --cask hyperdock
brew install --cask ticktick
brew install --cask notion
brew install --cask 1password
